# Docker
# Build a Docker image

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'robsonngr/ansible'
  imageVersion: '1.0'
  dockerFile: 'Dockerfile_ansible'
  tag: '$(Build.BuildId)'

steps:
- script: |
    docker build -f $(dockerFile) -t $(imageName):$(imageVersion) .
    docker images