# Docker
# Build a Docker image

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'ansible:$(Build.BuildId)'
#  imageVersion: '1.0'
  dockerFile: 'Dockerfile_ansible'
#  tag: '$(Build.BuildId)'

steps:
- script: |
    docker build -f $(dockerFile) -t $(dockerId)/$(imageName) .
    docker images
    docker login -u $(dockerId) -p $(DOCKERHUB_TOKEN)
    docker push $(dockerId)/$(imageName)